server:
  port: 8080

spring:
  application:
     name: student
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://47.93.184.44:3306/student?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
     username: root
     password: Shuyumeng2!

feign:
  hystrix:
    enabled: true
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  profiles:
    include: test
  cloud:
    bus:
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    #    ip-address:  #强制指定IP地址，默认会获取本机的IP地址
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）

logging:
  level:
    root: Info