server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.184.44:3306/student?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Shuyumeng2!
  profiles:
    include: test
    cloud:
      bus:
        refresh:
          enabled: true
  kafka:
    bootstrap-servers: localhost:9092

feign:
  hystrix:
    enabled: true
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

logging:
  level:
    root: info
    com:
      example:
        teacher:
          mapper: debug